# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/muszak/templates/NA-templates

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/muszak/templates/NA-templates

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/muszak/templates/NA-templates/CMakeFiles /home/muszak/templates/NA-templates/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/muszak/templates/NA-templates/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named run-all

# Build rule for target.
run-all: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run-all
.PHONY : run-all

# fast build rule for target.
run-all/fast:
	$(MAKE) -f CMakeFiles/run-all.dir/build.make CMakeFiles/run-all.dir/build
.PHONY : run-all/fast

#=============================================================================
# Target rules for targets named 11-algos

# Build rule for target.
11-algos: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 11-algos
.PHONY : 11-algos

# fast build rule for target.
11-algos/fast:
	$(MAKE) -f 10-algos/CMakeFiles/11-algos.dir/build.make 10-algos/CMakeFiles/11-algos.dir/build
.PHONY : 11-algos/fast

#=============================================================================
# Target rules for targets named run-11-algos

# Build rule for target.
run-11-algos: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run-11-algos
.PHONY : run-11-algos

# fast build rule for target.
run-11-algos/fast:
	$(MAKE) -f 10-algos/CMakeFiles/run-11-algos.dir/build.make 10-algos/CMakeFiles/run-11-algos.dir/build
.PHONY : run-11-algos/fast

#=============================================================================
# Target rules for targets named run-10-all

# Build rule for target.
run-10-all: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run-10-all
.PHONY : run-10-all

# fast build rule for target.
run-10-all/fast:
	$(MAKE) -f 10-algos/CMakeFiles/run-10-all.dir/build.make 10-algos/CMakeFiles/run-10-all.dir/build
.PHONY : run-10-all/fast

#=============================================================================
# Target rules for targets named run-20-all

# Build rule for target.
run-20-all: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run-20-all
.PHONY : run-20-all

# fast build rule for target.
run-20-all/fast:
	$(MAKE) -f 20-type-template/CMakeFiles/run-20-all.dir/build.make 20-type-template/CMakeFiles/run-20-all.dir/build
.PHONY : run-20-all/fast

#=============================================================================
# Target rules for targets named run-23-wrapped-optional

# Build rule for target.
run-23-wrapped-optional: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run-23-wrapped-optional
.PHONY : run-23-wrapped-optional

# fast build rule for target.
run-23-wrapped-optional/fast:
	$(MAKE) -f 20-type-template/CMakeFiles/run-23-wrapped-optional.dir/build.make 20-type-template/CMakeFiles/run-23-wrapped-optional.dir/build
.PHONY : run-23-wrapped-optional/fast

#=============================================================================
# Target rules for targets named 21-container-wrapper

# Build rule for target.
21-container-wrapper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 21-container-wrapper
.PHONY : 21-container-wrapper

# fast build rule for target.
21-container-wrapper/fast:
	$(MAKE) -f 20-type-template/CMakeFiles/21-container-wrapper.dir/build.make 20-type-template/CMakeFiles/21-container-wrapper.dir/build
.PHONY : 21-container-wrapper/fast

#=============================================================================
# Target rules for targets named run-21-container-wrapper

# Build rule for target.
run-21-container-wrapper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run-21-container-wrapper
.PHONY : run-21-container-wrapper

# fast build rule for target.
run-21-container-wrapper/fast:
	$(MAKE) -f 20-type-template/CMakeFiles/run-21-container-wrapper.dir/build.make 20-type-template/CMakeFiles/run-21-container-wrapper.dir/build
.PHONY : run-21-container-wrapper/fast

#=============================================================================
# Target rules for targets named 22-invalid

# Build rule for target.
22-invalid: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 22-invalid
.PHONY : 22-invalid

# fast build rule for target.
22-invalid/fast:
	$(MAKE) -f 20-type-template/CMakeFiles/22-invalid.dir/build.make 20-type-template/CMakeFiles/22-invalid.dir/build
.PHONY : 22-invalid/fast

#=============================================================================
# Target rules for targets named 23-wrapped-optional

# Build rule for target.
23-wrapped-optional: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 23-wrapped-optional
.PHONY : 23-wrapped-optional

# fast build rule for target.
23-wrapped-optional/fast:
	$(MAKE) -f 20-type-template/CMakeFiles/23-wrapped-optional.dir/build.make 20-type-template/CMakeFiles/23-wrapped-optional.dir/build
.PHONY : 23-wrapped-optional/fast

#=============================================================================
# Target rules for targets named run-30-all

# Build rule for target.
run-30-all: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run-30-all
.PHONY : run-30-all

# fast build rule for target.
run-30-all/fast:
	$(MAKE) -f 30-traits/CMakeFiles/run-30-all.dir/build.make 30-traits/CMakeFiles/run-30-all.dir/build
.PHONY : run-30-all/fast

#=============================================================================
# Target rules for targets named 31-traits

# Build rule for target.
31-traits: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 31-traits
.PHONY : 31-traits

# fast build rule for target.
31-traits/fast:
	$(MAKE) -f 30-traits/CMakeFiles/31-traits.dir/build.make 30-traits/CMakeFiles/31-traits.dir/build
.PHONY : 31-traits/fast

#=============================================================================
# Target rules for targets named run-31-traits

# Build rule for target.
run-31-traits: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run-31-traits
.PHONY : run-31-traits

# fast build rule for target.
run-31-traits/fast:
	$(MAKE) -f 30-traits/CMakeFiles/run-31-traits.dir/build.make 30-traits/CMakeFiles/run-31-traits.dir/build
.PHONY : run-31-traits/fast

#=============================================================================
# Target rules for targets named 32-interesting

# Build rule for target.
32-interesting: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 32-interesting
.PHONY : 32-interesting

# fast build rule for target.
32-interesting/fast:
	$(MAKE) -f 30-traits/CMakeFiles/32-interesting.dir/build.make 30-traits/CMakeFiles/32-interesting.dir/build
.PHONY : 32-interesting/fast

#=============================================================================
# Target rules for targets named run-32-interesting

# Build rule for target.
run-32-interesting: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run-32-interesting
.PHONY : run-32-interesting

# fast build rule for target.
run-32-interesting/fast:
	$(MAKE) -f 30-traits/CMakeFiles/run-32-interesting.dir/build.make 30-traits/CMakeFiles/run-32-interesting.dir/build
.PHONY : run-32-interesting/fast

#=============================================================================
# Target rules for targets named run-40-all

# Build rule for target.
run-40-all: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run-40-all
.PHONY : run-40-all

# fast build rule for target.
run-40-all/fast:
	$(MAKE) -f 40-algos-impl/CMakeFiles/run-40-all.dir/build.make 40-algos-impl/CMakeFiles/run-40-all.dir/build
.PHONY : run-40-all/fast

#=============================================================================
# Target rules for targets named run-43-vector-erase

# Build rule for target.
run-43-vector-erase: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run-43-vector-erase
.PHONY : run-43-vector-erase

# fast build rule for target.
run-43-vector-erase/fast:
	$(MAKE) -f 40-algos-impl/CMakeFiles/run-43-vector-erase.dir/build.make 40-algos-impl/CMakeFiles/run-43-vector-erase.dir/build
.PHONY : run-43-vector-erase/fast

#=============================================================================
# Target rules for targets named 43-vector-erase

# Build rule for target.
43-vector-erase: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 43-vector-erase
.PHONY : 43-vector-erase

# fast build rule for target.
43-vector-erase/fast:
	$(MAKE) -f 40-algos-impl/CMakeFiles/43-vector-erase.dir/build.make 40-algos-impl/CMakeFiles/43-vector-erase.dir/build
.PHONY : 43-vector-erase/fast

#=============================================================================
# Target rules for targets named 41-find-if

# Build rule for target.
41-find-if: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 41-find-if
.PHONY : 41-find-if

# fast build rule for target.
41-find-if/fast:
	$(MAKE) -f 40-algos-impl/CMakeFiles/41-find-if.dir/build.make 40-algos-impl/CMakeFiles/41-find-if.dir/build
.PHONY : 41-find-if/fast

#=============================================================================
# Target rules for targets named run-41-find-if

# Build rule for target.
run-41-find-if: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run-41-find-if
.PHONY : run-41-find-if

# fast build rule for target.
run-41-find-if/fast:
	$(MAKE) -f 40-algos-impl/CMakeFiles/run-41-find-if.dir/build.make 40-algos-impl/CMakeFiles/run-41-find-if.dir/build
.PHONY : run-41-find-if/fast

#=============================================================================
# Target rules for targets named 42-inner-product

# Build rule for target.
42-inner-product: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 42-inner-product
.PHONY : 42-inner-product

# fast build rule for target.
42-inner-product/fast:
	$(MAKE) -f 40-algos-impl/CMakeFiles/42-inner-product.dir/build.make 40-algos-impl/CMakeFiles/42-inner-product.dir/build
.PHONY : 42-inner-product/fast

#=============================================================================
# Target rules for targets named run-42-inner-product

# Build rule for target.
run-42-inner-product: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run-42-inner-product
.PHONY : run-42-inner-product

# fast build rule for target.
run-42-inner-product/fast:
	$(MAKE) -f 40-algos-impl/CMakeFiles/run-42-inner-product.dir/build.make 40-algos-impl/CMakeFiles/run-42-inner-product.dir/build
.PHONY : run-42-inner-product/fast

#=============================================================================
# Target rules for targets named run-50-all

# Build rule for target.
run-50-all: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run-50-all
.PHONY : run-50-all

# fast build rule for target.
run-50-all/fast:
	$(MAKE) -f 50-sfinae/CMakeFiles/run-50-all.dir/build.make 50-sfinae/CMakeFiles/run-50-all.dir/build
.PHONY : run-50-all/fast

#=============================================================================
# Target rules for targets named 51-traits

# Build rule for target.
51-traits: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 51-traits
.PHONY : 51-traits

# fast build rule for target.
51-traits/fast:
	$(MAKE) -f 50-sfinae/CMakeFiles/51-traits.dir/build.make 50-sfinae/CMakeFiles/51-traits.dir/build
.PHONY : 51-traits/fast

#=============================================================================
# Target rules for targets named run-51-traits

# Build rule for target.
run-51-traits: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run-51-traits
.PHONY : run-51-traits

# fast build rule for target.
run-51-traits/fast:
	$(MAKE) -f 50-sfinae/CMakeFiles/run-51-traits.dir/build.make 50-sfinae/CMakeFiles/run-51-traits.dir/build
.PHONY : run-51-traits/fast

#=============================================================================
# Target rules for targets named 52-void_t

# Build rule for target.
52-void_t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 52-void_t
.PHONY : 52-void_t

# fast build rule for target.
52-void_t/fast:
	$(MAKE) -f 50-sfinae/CMakeFiles/52-void_t.dir/build.make 50-sfinae/CMakeFiles/52-void_t.dir/build
.PHONY : 52-void_t/fast

#=============================================================================
# Target rules for targets named run-52-void_t

# Build rule for target.
run-52-void_t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run-52-void_t
.PHONY : run-52-void_t

# fast build rule for target.
run-52-void_t/fast:
	$(MAKE) -f 50-sfinae/CMakeFiles/run-52-void_t.dir/build.make 50-sfinae/CMakeFiles/run-52-void_t.dir/build
.PHONY : run-52-void_t/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... run-all"
	@echo "... 11-algos"
	@echo "... run-11-algos"
	@echo "... run-10-all"
	@echo "... run-20-all"
	@echo "... run-23-wrapped-optional"
	@echo "... 21-container-wrapper"
	@echo "... run-21-container-wrapper"
	@echo "... 22-invalid"
	@echo "... 23-wrapped-optional"
	@echo "... run-30-all"
	@echo "... 31-traits"
	@echo "... run-31-traits"
	@echo "... 32-interesting"
	@echo "... run-32-interesting"
	@echo "... run-40-all"
	@echo "... run-43-vector-erase"
	@echo "... 43-vector-erase"
	@echo "... 41-find-if"
	@echo "... run-41-find-if"
	@echo "... 42-inner-product"
	@echo "... run-42-inner-product"
	@echo "... run-50-all"
	@echo "... 51-traits"
	@echo "... run-51-traits"
	@echo "... 52-void_t"
	@echo "... run-52-void_t"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

